### ISSUE TITLE
제가 git 초보자라서 그런데 main.py 실행 어떻게 시키는건가요?

### ISSUE THREAD

**Issue by weddingsue** [dltkddnr04/AfreecaTV-Auto-Recorder#2]
자세히 설명 부탁드립니다 ㅠ.ㅠ

**Comment by dltkddnr04** [comment]
1. 패키지 리스트 업데이트 및 요구 패키지 설치
`sudo apt update`
`sudo apt install python3 python3-requests streamlink git`

2. 리포지토리 클론
`sudo git clone https://github.com/dltkddnr04/AfreecaTV-Auto-Recorder`

3. 디렉토리 진입
`cd AfreecaTV-Auto-Recorder`

4. main.py 실행
`sudo python3 main.py 방송인닉네임`

순입니다.
이 스크립트는 프로그램이 실행되는 경로에 영상 파일을 저장하기 때문에 'AfreecaTV-Auto-Recorder' 폴더 안에 방송인 닉네임 폴더가 생기고, 그 안에 영상 파일이 저장됩니다.

만약 다른 경로에 영상을 저장해야 된다면, 상대경로를 사용하여 실행하시는 방법이 있습니다.
예시('AfreecaTV-Auto-Recorder' 폴더 위에 영상을 저장하는 폴더 'archive'가 있는경우)
`cd archive`
`sudo python3 ../AfreecaTV-Auto-Recorder/main.py 방송인닉네임`

그런데 이 프로젝트는 아프리카 티비 내부 구조를 뜯어보고 문서로 정리해서 다른사람이 비슷한 프로그램 개발할때 참고할 수 있게끔 하는 목적이 더 큽니다.
Linux 환경에서 개인적으로 돌릴걸 상정하고 작성한 코드이기 때문에 오류도 많고 100%의 가용성을 보장하지도 않습니다.

그래서 만약 이 코드를 실제 녹화 용도로 사용하시려는거라면 차라리 [L.E.D](https://led.hi098123.com) 같은 상용 프로그램을 쓰는걸 강하게 권장합니다.
