### ISSUE TITLE
혹시 soop 으로 바뀐거 업뎃 가능할까요? ㅠ..

### ISSUE THREAD

**Issue by Honinbo-Shusaku** [dltkddnr04/AfreecaTV-Auto-Recorder#6]
진짜 잘 쓰고 있었는데 드디어 오늘부터 안되기 시작하네요....
너무 편했는데 흑흑... 님께 최고였어요....... 어떻게 안될까요

**Comment by dltkddnr04** [comment]
이 리포지토리는 트위치 대한민국 철수 당시 아프리카TV를 선택했던 단 한명의 방송인 때문에 시작했다가 그분이 다시 치지직에서 방송하면서 일년 가까이 방치했던 코드입니다.
다시말해서 저는 현재 해당 코드의 실사용자가 아닙니다.

하지만 이번 아프리카TV -> SOOP 의 경우에는 서버 주소 변경 이외의 변경점이 없었습니다.
또한 추후에도 큰 변화점이 있지는 않을것이라고 생각됩니다.

이번 대응은 제가 마침 여유가 있어서 가능했지만, 추후 서버 구조가 크게 바뀐다면 적극적인 업데이트를 기대하시기에는 어려운 상황입니다.
이점 양해바랍니다.
